GET http://localhost:3001/api/notes
####
DELETE  http://localhost:3001/api/notes/5
###
GET  http://localhost:3001/api/notes/61343adecd0e26b2e0e469f2
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "SEND BY THE REST CLIENT ON VS CODE",
    "important": true
}
###
PUT http://localhost:3001/api/notes/61356dd26e54e81dd85d99a8
Content-Type: application/json

{
    "content": "VS Code REST Client is good as POSTMAN",
    "date": "2021-09-06T01:24:34.415Z",
    "id": "61356dd26e54e81dd85d99a8",
    "important": false
}